version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: space_backend
    depends_on:
      - postgres
    environment:
      - APOLLO_KEY=service:SpaceX-83gisc:J8xmxkwbTwS7CTMsCiUsuA
      - DATABASE_HOST=postgres
      - DATABASE_NAME=space
      - DATABASE_PASSWORD=secret
      - DATABASE_PORT=5432
      - DATABASE_USER=docker
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/app/
      - /app/node_modules/

  frontend:
    build:
      context: ./frontend
    container_name: space_frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app/
      - /app/node_modules/

  postgres:
    container_name: space_postgres
    environment:
      POSTGRES_DB: space
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: docker
    image: postgres:13-alpine
    ports:
      - 5432:5432
